alias r1='clang rynn.c -o rynn && ./rynn'
alias e1='micro rynn.c'
alias r2='clang rynnn.c -o rynnn &&  ./rynnn'
alias e2='micro rynnn.c'
alias r3='clang bro.c -o bro && ./bro'
alias e3='micro bro.c'
alias r4='clang coba.c -o coba && ./coba'
alias e4='micro coba.c'
